language: java

cache:
  directories:
  - $HOME/.m2

script:
  - mvn package -B
  - mkdir deploy
  - unzip -d deploy/cobalt-eclipse-sdk com.eidosmedia.cobalt.eclipse.sdk.repository/target/com.eidosmedia.cobalt.eclipse.sdk.repository-*.zip

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: deploy
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  repo: EidosMedia/eidosmedia.github.io
  target_branch: master
