language: java

cache:
  directories:
  - $HOME/.m2

script:
  - mvn package -B
  - unzip -d cobalt-eclipse-sdk com.eidosmedia.cobalt.eclipse.sdk.repository/target/com.eidosmedia.cobalt.eclipse.sdk.repository-*.zip

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: cobalt-eclipse-sdk
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  repo: EidosMedia/eidosmedia.github.io/cobalt-eclipse-sdk
 #target_branch: master
